In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("Z:/csv/casos_diagnostico_ccaa.csv", nrows=1e6)

In [8]:
df.dtypes

ccaa_iso                        object
fecha                           object
num_casos                        int64
num_casos_prueba_pcr             int64
num_casos_prueba_test_ac         int64
num_casos_prueba_ag              int64
num_casos_prueba_elisa           int64
num_casos_prueba_desconocida     int64
dtype: object

In [13]:
df.groupby(by = 'ccaa_iso')['num_casos'].describe()

          count         mean          std  min    25%    50%     75%     max
ccaa_iso
AN        379.0   777.058047  1112.765175  0.0   12.0  211.0  1083.0  4677.0
AR        379.0   224.910290   250.053089  0.0   12.5  169.0   349.5  1152.0
AS        379.0    77.361478   122.837113  0.0    0.5   26.0    93.0   801.0
CB        379.0    51.794195    62.018899  0.0    1.0   27.0    81.0   263.0
CE        379.0     8.897098    14.779776  0.0    0.0    2.0    11.0    75.0
CL        379.0   383.208443   470.435615  0.0   16.5  217.0   593.5  2033.0
CM        379.0   300.021108   316.388348  0.0   22.5  146.0   555.5  1386.0
CN        379.0    79.617414    87.992838  0.0    2.0   30.0   142.5   310.0
CT        379.0  1090.688654  1198.153749  0.0  140.5  842.0  1440.0  5739.0
EX        379.0   128.192612   205.652626  0.0    3.0   32.0   184.0  1491.0
GA        379.0   184.728232   210.735742  0.0    6.0  105.0   310.0  1099.0
IB        379.0   112.263852   147.920878  0.0    4.0   38.0   186.0   766.0
MC        379.0   187.287599   257.103471  0.0    2.0   49.0   331.5  1072.0
MD        379.0  1157.997361  1308.561300  0.0   83.0  764.0  1831.0  6748.0
ML        379.0    12.986807    20.654562  0.0    0.0    2.0    20.0    99.0
NC        379.0   117.147757   144.912980  0.0    6.0   80.0   151.5   734.0
PV        379.0   310.406332   339.985222  0.0   19.0  227.0   468.5  1457.0
RI        379.0    53.614776    59.171255  0.0    1.0   34.0    95.0   268.0
VC        379.0   484.216359   625.873367  0.0   11.0  197.0   661.0  3081.0

In [14]:
np.corrcoef(df["num_casos"],df["num_casos_prueba_pcr"]) #gives the correlation coefficient - always symmetric and with diagonal 1

array([[1.        , 0.96976446],
       [0.96976446, 1.        ]])

In [18]:
np.corrcoef([df["num_casos"],df["num_casos_prueba_pcr"],df["num_casos_prueba_ag"]])

array([[1.        , 0.96976446, 0.584733  ],
       [0.96976446, 1.        , 0.36929243],
       [0.584733  , 0.36929243, 1.        ]])

In [19]:
df.corr() #correlations matrix

,num_casos,num_casos_prueba_pcr,num_casos_prueba_test_ac,num_casos_prueba_ag,num_casos_prueba_elisa,num_casos_prueba_desconocida
num_casos,1.000000,0.969764,0.000905,0.584733,0.145598,0.123331
num_casos_prueba_pcr,0.969764,1.000000,0.002343,0.369292,0.167886,0.144121
num_casos_prueba_test_ac,0.000905,0.002343,1.000000,-0.031760,0.006121,0.004682
num_casos_prueba_ag,0.584733,0.369292,-0.031760,1.000000,-0.024513,-0.025989
num_casos_prueba_elisa,0.145598,0.167886,0.006121,-0.024513,1.000000,0.134665
num_casos_prueba_desconocida,0.123331,0.144121,0.004682,-0.025989,0.134665,1.000000

In [20]:
corr = round(df.corr(),3) #correlations matrix rounded to 3 decimal numbers
corr.style.background_gradient() #graph

Matplotlib is building the font cache; this may take a moment.